# Generated by Django 3.1.6 on 2021-02-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='list_name',
        ),
    ]
