# Generated by Django 3.1.6 on 2021-02-10 23:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colours',
            name='name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Brown', 'Brown'), ('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Pink', 'brown'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Green', 'Green'), ('Pink', 'Pink'), ('Gray', 'Gray')], max_length=68, null=True),
        ),
    ]
