# Generated by Django 3.1.6 on 2021-02-11 23:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210210_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colours',
            name='name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Brown', 'Brown'), ('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Green', 'Green'), ('Pink', 'Pink'), ('Gray', 'Gray')], max_length=63, null=True),
        ),
        migrations.DeleteModel(
            name='Price_list',
        ),
    ]
