# Generated by Django 3.1.6 on 2021-02-15 13:43

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_has_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', multiselectfield.db.fields.MultiSelectField(choices=[('over_50', 'over_50'), ('over_100', 'over_100'), ('over_150', 'over_150'), ('over_200', 'over_200'), ('over_250', 'over_250'), ('over_300', 'over_300')], max_length=52, null=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name_plural': 'PriceList',
            },
        ),
    ]
