# Generated by Django 3.1.6 on 2021-02-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210223_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(help_text='Sizes offered', to='products.Size'),
        ),
    ]
