# Generated by Django 3.1.6 on 2021-02-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210223_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=50),
        ),
    ]
